name: Deploy Static Site to S3

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Intermediate Step 
      - name: Imprimir
        run: echo ${{ secrets.AWS_ACCESS_KEY_ID }}

      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Upload to S3
        uses: bwcxyk/s3-sync-action@1.0.0
        with:
          args: --acl public-read --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}